# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build
      run: go build -v
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}_${{ github.sha }}_build
        path: lfs-s3*
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.sha}}
        release_name: Release v${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./lfs-s3*
        asset_name: lfs-s3-${{ matrix.os }}
        asset_content_type: application/octet-stream

    
